-- MySQL Script generated by MySQL Workbench
-- mar 04 jul 2017 17:00:03 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `phone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acount` (
  `idAcount` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`idAcount`),
  UNIQUE INDEX `idAcount_UNIQUE` (`idAcount` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail` (
  `idDetail` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `idAcount` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetail`),
  UNIQUE INDEX `idDetail_UNIQUE` (`idDetail` ASC),
  INDEX `fk_detail_acount1_idx` (`idAcount` ASC),
  INDEX `fk_detail_user1_idx` (`email` ASC),
  CONSTRAINT `fk_detail_acount1`
    FOREIGN KEY (`idAcount`)
    REFERENCES `mydb`.`acount` (`idAcount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
